#+HUGO_BASE_DIR: .
#+MACRO: uva @@hugo:{{<UVa2 number="$1" >}}@@


* Docs
:PROPERTIES:
:HUGO_SECTION: docs
:EXPORT_HUGO_SECTION: docs
:END:

** Why Take This Course?
:PROPERTIES:
:EXPORT_FILE_NAME: why-take-this-course
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 1 :date 2022-08-22 :publishdate 2022-07-01
:END:

Welcome to Competitive Programming!  In this class you will learn how to compete in programming contests such as ICPC,
Code Forces, and Hacker Rank.  *Is this class for you?  Read on to find out...*

*** What Are the Benefits of Competitive Programming?

Participating in coding contests has benefits!

  You will
  - build confidence in your coding skills,
  - increase your coding speed,
  - be ready to crush a coding interview,
  - and quite possibly make some friends!

*** But... I'm not very competitive, and besides, I'll never beat those top students!

That doesn't matter!  Whether you are just starting out or whether you are competing for a chance at the World Finals,
the only person you're really trying to beat is yourself.  The goal is to try hard, do a little bit better than last time,
or perhaps learn something that will help you next time.  You can do practice problems on your own, but there's nothing
like a contest to keep you honest.

*** Am I ready for this course?

The only prerequisite is that we assume you know how to program.  We don't even assume you're any good at it... this course
will help with that part.  But if you have programmed in Python, C, or C++ then you are ready for this course.

It does help if you've taken data structures and a theory course... but you can get started now and take those later as you
get stronger.

** Getting Started
:PROPERTIES:
:EXPORT_FILE_NAME: getting-started
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 2 :date 2022-08-22 :publishdate 2022-07-01
:END:

*** How Do I Get Started?

  - Join the CampusWire forum.  If you registered before class started, you should have gotten an invite.  If you registered late,
    or did not get the invite, you need to email the instructor.
  - It is recommended that you get these books:
    - [[https://cpbook.net][Competitive Programming 4]].  It is a two book set.
    - [[https://link.springer.com/book/10.1007/978-3-319-72547-5][Guide to Competitive Programming]].  As of this writing the PDF is free.
  - Register on [[https://codeforces.com][Code Forces]].  Your username *will be visible* to other students; you can create a "throwaway"
    account if you want just for this course.
    - Once you are registered, join [[https://codeforces.com/group/PHxDiFeaeq/contests][the class group]].  This is where your problems
      will be hosted.

*** How do I get good at this?

Practice.  A lot.  But do it efficiently...

  - Attend contests as much as you can.
    - [[https://codeforces.com][Code Forces]] has two hour long contests usually once or twice a week, for instance.
    - After the contest is over, read the commentary, both for the problems you solved, and the problems you attempted and could not solve.
    - Upsolve the ones you couldn't do.  (I don't know why they call it upsolving.)  This means that you go back to the computer, finish
      your solution, and submit it until you get it accepted.
  - Solve practice problems
    - This has a similar feel, but in this case it's okay get help.  If you are solving UVa problems you can use the UDebug and UHunt
      sites for extra hints / sample inputs.

** Syllabus
:PROPERTIES:
:EXPORT_FILE_NAME: syllabus
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 3 :date 2022-08-22 :publishdate 2022-07-01
:END:

*** Location and Times

  - Course Title: Introduction to Competitive Programming
  - Rubric: CS 491 CAP
  - CRN: 31584
  - Dates: August 22 to December 8th, 2022, Mondays and Wednesdays
  - Time: 15:30 &ndash; 16:45
  - Location:
    - On Campus: 1302 Siebel Center
  - Instructor: Mattox Beckman
  - Recommended Textbooks:
     - [[https://cpbook.org][Competitive Programming 4]]
     - [[https://link.springer.com/book/10.1007/978-3-319-72547-5][Guide to Competitive Programming]]
  - Prerequisites: ability to program is necessary; CS 225 recommended.  We will use C++ for our content, but you are welcome to use
    a different language.
  - Office Hours: tba

*** Purpose

The purpose of this course is to prepare you to compete in ICPC-style competitive programming contests.  While this will help
you compete in the Illinois Programming League, Hacker Rank, Code Forces, or similar contests, learning this material has been shown
to help with programming assignments in other courses, and many students learn this material to become confident and skillful in coding
interviews.

*** Objectives and Outcomes

Upon successfully completing this course, you will have solved many programming problems.  You will have learned to select the correct
algorithm depending on the problem constraints and available time and memory resources.  You will have learned to implement your
solutions quickly and accurately, being given minimal guidance if your solution is incorrect.  You will have learned to work on your own
and in an ICPC style team of students using one computer.  And hopefully you will have a lot of fun doing so!

*** Class Structure

This is a flipped classroom.  You will be given a reading from the textbook, a short video to watch, and a sample problem or two to solve before class.
During class the instructor will ask for student comments about the problems and give commentary.   Afterward, there will be one or two more problems
for you to do during class.  Sometimes you will be asked to solve them individually, sometimes you will be placed in a team.  Once every two weeks we
will also release a problem set with a variety of problems to give you practice picking the correct algorithm to use.

*** Assignments and Grading

This course is a Credit/No Credit course.  To get credit, you must complete 70% of the class-related problems, attend at least 70% of
the class sessions (or have made other arrangements), and complete six of the given bi-weekly
problem sets.  You may also get problem set credit by competing in an ICPC tryout or other significant externally held contest.

We will also have an assignment where you prepare a Team Reference Document.  This assignment is not required, but highly recommended.

*** Students with Disabilities

To obtain disability-related academic adjustments and/or auxiliary aids,
students with disabilities must contact the course instructor as soon as
possible. To insure that disability-related concerns are properly
addressed from the beginning, students with disabilities who require
assistance to participate in this class should contact disability
resources and educational services
([[https://www.disability.illinois.edu/)][DRES]] and see the instructor
as soon as possible. If you need accommodations for any sort of
disability, please speak to me after class, or make an appointment to
see me, or see me during my office hours. DRES provides students with
academic accommodations, access, and support services. To contact DRES
you may visit 1207 S. Oak St., Champaign, call 333-4603 (v/tdd), or
e-mail a message to [[mailto:disability@uiuc.edu][disability@uiuc.edu]].

*** Emergency Response Recommendations

The university police have posted some [[http://police.illinois.edu/emergency/][emergency response recommendations]]. I
encourage you to review this website and the campus building
[[http://police.illinois.edu/emergency-preparedness/building-emergency-action-plans/][floor plans website]]
within the first 10 days of class.

Of course, since we're all online, your classroom is likely your living space.  Have you considered making
a fire safety plan with your family or roommates?

*** Family Educational Rights and Privacy Act (FERPA)


Any student who has suppressed their directory information pursuant to family
educational rights and privacy act (FERPA) should self-identify to the
instructor to ensure protection of the privacy of their attendance in this
course. see the [[http://registrar.illinois.edu/ferpa][FERPA]] site for more information.

*** Mental Health

Diminished mental health, including significant stress, mood changes, excessive
worry, substance/alcohol abuse, or problems with eating and/or sleeping can
interfere with optimal academic performance, social development, and emotional
wellbeing. The University of Illinois offers a variety of confidential services
including individual and group counseling, crisis intervention, psychiatric
services, and specialized screenings at no additional cost. If you or someone
you know experiences any of the above mental health concerns, it is strongly
encouraged to contact or visit any of the University's resources provided below.
Getting help is a smart and courageous thing to do -- for yourself and for those
who care about you.

Counseling Center: 217-333-3704, 610 East John Street Champaign, IL 61820

McKinley Health Center:217-333-2700, 1109 South Lincoln Avenue, Urbana, Illinois 61801

This is where the syllabus will be.

* Lectures
:PROPERTIES:
:HUGO_SECTION: lectures
:EXPORT_HUGO_SECTION: lectures
:END:

** Template :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: template
:END:

*** Synopsis


*** Slides


** Course Introduction
:PROPERTIES:
:ID:       d6691455-f4dc-44ec-b6ae-2b169766e1af
:EXPORT_FILE_NAME: course-introduction
:END:

Welcome to Competitive Programming!  Today we will talk about the benefits of competitive programming, the course structure, and the tools we will
use in the course.

** IO
:PROPERTIES:
:EXPORT_FILE_NAME: io
:END:

The first thing your program needs to do is read in the test data and convert it to an internal structure.
There are several patterns that test cases follow, and you will need to handle each one a bit differently.
It all comes down to knowing how much data you are going to get.  There are three primary ways you find this out:

- An explicit count
- A special marker (like a terminating zero)
- Simply getting an end-of-file

We will also talk about formatting options.

We don't have a video for this lecture, but here are some slides with all the content.

- [[../../slides/io-slides.pdf][IO Slides]]

The problems for this class are at

- [[https://codeforces.com/group/PHxDiFeaeq/contest/372486][IO Problems]]

** Dictionaries and Sets
:PROPERTIES:
:EXPORT_FILE_NAME: dictionaries-and-sets
:END:

We will talk about how to create dictionaries in C++ and in [[class:sc][Python]], and some of the operations available to you.

- [[../../slides/dictionaries-and-sets-slides.pdf][Dictionaries and Sets Slides]]
- [[https://mediaspace.illinois.edu/media/t/1_jk9tjhx0][Dictionaries and Sets Video]]

The problems for this class are at

- [[https://codeforces.com/group/PHxDiFeaeq/contest/372486][IO Problems]]

** Prime Numbers
:PROPERTIES:
:EXPORT_FILE_NAME: prime-numbers
:END:

*** Video

  - [[../../videos/sieve-of-eratosthenes][Sieve of Eratosthenes]]

*** Recommended Reading

  - Competitive Programming 4, section 5.3.1--5

** Minimum Spanning Trees
:PROPERTIES:
:EXPORT_FILE_NAME: minimum-spanning-trees
:END:

*** Synopsis

Last time we talked about graph representations and reviewed disjoint sets.  Now we will use that to solve
minimum spanning tree problems.

*** Slides

- [[../../slides/minimum-spanning-trees-slides.pdf][Minimum Spanning Trees Slides]]

** Graph Traversals, Part 1
:PROPERTIES:
:EXPORT_FILE_NAME: graph-traversals-1
:END:

*** Synopsis

We will go over the basic implementations of DFS and BFS, and show a couple of simple applications like
flood fill, connected components, and topological sort.

*** Slides

- [[../../slides/graph-traversals-1-slides.pdf][Graph Traversals 1]]

** Graph Traversals, Part 2
:PROPERTIES:
:EXPORT_FILE_NAME: graph-traversals-2
:END:

*** Synopsis

This lecture will cover more advanced use of BFS and DSF, such as checking if a graph is bipartite, finding cut edges, and finding articulation points.

*** Slides

- [[../../slides/graph-traversals-2-slides.pdf][Graph Traversals 2]]

** Single Source Shortest Path
:PROPERTIES:
:EXPORT_FILE_NAME: single-source-shortest-path
:END:

*** Synopsis

We will show how to use breadth first search to find shortest paths in unweighted graphs, and Dijkstra's algorithm for weighted graphs.

You will have to wait to find out what to do about negative weight cycles!

*** Slides

- [[../../slides/bfs-shortest-path-slides.pdf][BFS Shortest Path]]
- [[../../slides/dijkstra-shortest-path-slides.pdf][Dijkstra Shortest Path]]

** All Pairs Shortest Path
:PROPERTIES:
:EXPORT_FILE_NAME: all-pairs-shortest-path
:END:

*** Synopsis

We will cover Bellman Ford, which handles negative weight cycles, and Floyd-Warshall, which gives the shortest path between every pair of points.

*** Slides

- [[../../slides/bellman-ford-and-spfa-slides.pdf][Bellman Ford and SPFA]]
- [[../../slides/floyd-warshall-slides.pdf][Floyd Warshall]]

** Greedy Algorithms
:PROPERTIES:
:EXPORT_FILE_NAME: greedy-algorithms
:END:

*** Synopsis

We will cover Bellman Ford, which handles negative weight cycles, and Floyd-Warshall, which gives the shortest path between every pair of points.

*** Slides

- [[../../slides/greedy-algorithms-slides.pdf][Greedy Algorithms]]

** Complete Search
:PROPERTIES:
:EXPORT_FILE_NAME: complete-search
:END:

*** Synopsis

Some classes of problems require you to check the entire search-space to find the solutions, possibly with the the ablility to prune search paths
that cannot yield the answer.

*** Slides

- [[../../slides/complete-search-slides.pdf][Complete Search]]

** Dynamic Programming
:PROPERTIES:
:EXPORT_FILE_NAME: dynamic-programming
:END:

*** Synopsis

If you have overlapping subproblems but do not have the greedy property, perhaps dynamic programming will help!

In this lecture we will talk about the exact change problem.

*** Slides

- [[../../slides/dynamic-programming-slides.pdf][Dynamic Programming]]


** DP 2 - LCS and LIS
:PROPERTIES:
:EXPORT_FILE_NAME: dp-2-lcs-lis
:END:

*** Synopsis

Another kind of DP problem!  This time we are looking for subsequences that have certain properties.

*** Slides

- [[../../slides/dp-2-lcs-lis-slides.pdf][DP 2 - LCS and LIS]]


** Classic String DP
:PROPERTIES:
:EXPORT_FILE_NAME: classic-string-dp
:END:

*** Synopsis

We will go over two classic problems for strings using DP:
- Edit distance (Levinstein Distance)
- Palindrome detection

*** Slides

- [[../../slides/classic-string-dp-slides.pdf][Classic String DP]]


** KMP
:PROPERTIES:
:EXPORT_FILE_NAME: kmp
:END:

*** Synopsis

We will go over the KMP string matching algorithm.

*** Slides

- [[../../slides/kmp-slides.pdf][KMP Algorithm]]

** Points, Lines, and Vectors
:PROPERTIES:
:EXPORT_FILE_NAME: points-lines-vectors
:END:
*** Slides

- [[../../slides/points-lines-vectors-slides.pdf][Points, Lines, and Vectors]]

** Shapes
:PROPERTIES:
:EXPORT_FILE_NAME: shapes
:END:

*** Slides
- [[../../slides/shapes.html][Shapes]]

** Convex Hull
:PROPERTIES:
:EXPORT_FILE_NAME: convex-hull
:END:

*** Slides
- [[../../slides/convex-hull.html][Convex Hull]]

** Combinatorics
:PROPERTIES:
:EXPORT_FILE_NAME: combinatorics
:END:

*** Slides
- [[../../slides/basic-combinatorics-slides.pdf][Basic Combinatorics]]

** Dynamic Programming Redux
:PROPERTIES:
:EXPORT_FILE_NAME: dynamic-programming-redux
:END:

** GCD and Diophantine
:PROPERTIES:
:EXPORT_FILE_NAME: gcd
:END:

*** Slides
- [[../../slides/gcd-slides.pdf][GCD and Diophantine]]

** Segment Trees
:PROPERTIES:
:EXPORT_FILE_NAME: segment-trees
:END:


* Videos
:PROPERTIES:
:HUGO_SECTION: videos
:EXPORT_HUGO_SECTION: videos
:END:
** The Sieve of Eratosthenes
:PROPERTIES:
:EXPORT_FILE_NAME: sieve-of-eratosthenes
:END:

*** Video
@@hugo:{{< awsvideo slug="sieve-of-eratosthenes" >}}@@

*** Slides

- [[../../slides/sieve-of-eratosthenes.pdf][Sieve of Eratosthenes Slides]]

*** Transcript

Hello, and welcome to Competitive Programming!  Today we are going to talk about calculating prime numbers, in
particular using the Sieve of Eratosthenes.

**** Objectives

Your objective it to be able to implement the Sieve, and also to explain some of the reasoning behind why it works.

You will also see some applications involving prime numbers.

**** Calculating Primes the Hard Way

Suppose you have a number =p= that you want to factor, or else discover if it is prime or not.

One thing you could do it just loop over all the numbers smaller than =p= and see if they divide =p= or not.

This, of course, is going to be slow.

**** Improvement 1 - skip the even numbers

We can double the speed with one simple observation: if we have already ruled out that the number is divisible by 2,
then we have also ruled out that it is divisible by any multiple of 2.

So here we check divisibility by 2 first, and then check all the odd numbers.

**** Improvement 2 - Stop at sqrt(p)

Another optimization is that we don't really need to check everything up to =p=.  We can check up to =p='s square root.

Here's why: suppose there is a factor $q$ that is bigger than the square root of p.  It can't be $p$ itself, since it is
smaller than $p$.  This means it must be multiplied by some factor $k$ so that $k q = p$.

Now, if $k$ is greater than the square root of $p$ then $k q$ itself would be greater than $p$.  Therefore, $k$ must be
smaller than $q$.  And if that's the case, then we would have already checked $k$ by the time we got to $q$.  So the
check on $q$ would be redundant.

This is good, so now we have a method that is ${\cal O}(\sqrt{p})$.  But we are still testing all the integers in that
range.  What we'd really like to do is only test the primes.

To do that we are going to have to make a list of the prime numbers.

**** The Sieve

Here is the code for the Sieve of Eratosthenes, developed by Eratosthenes of Alexandria.

We will use a bitset called =bs= to keep track of the integers and whether or not they are prime.  We will also keep a
vector =primes= to have the list handy.

When we start off, we set all the bit in =bs= to 1 to indicate that they are prime.  The sieve is going to work by
zeroing out all the elements that are a multiple of a prime.

To start, we zero out elements 0 and 1, and then enter our main loop.  The i loop checks the bit set until it finds the
next prime number.  Then the j loop starts off at i squared and crosses out the multiples of i.  Once that is done, we
put that prime i into the list of primes.

That's it.  The algorithm runs in ${\cal O}(n \log \log n)$, roughly.

On my laptop, purchased in 2017, it could calculate the primes lower than 10 million in one twentieth of a second.  It
calculated the primes to 100 million in less than one second, but in many problems that will put you dangerously close
to the time limit.

**** Factoring Integers

One important applications of primes is factoring integers.  Here is the code.  You do it by starting with 2 and
incrementally picking the next largest prime number.  If you find a prime that is a factor, divide it off repeatedly
until it's not a factor anymore, and then move to the next prime.

* End :noexport:
;; Local Variables:
;; eval: (org-link-set-parameters "class" :export #'my-org-export-class-link)
;; End:
