#+HUGO_BASE_DIR: .
#+MACRO: uva @@hugo:{{<UVa2 number="$1" >}}@@


* Docs
:PROPERTIES:
:HUGO_SECTION: docs
:EXPORT_HUGO_SECTION: docs
:END:

** Why Take This Course?
:PROPERTIES:
:EXPORT_FILE_NAME: why-take-this-course
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 1 :date 2022-08-22 :publishdate 2022-07-01
:END:

Welcome to Competitive Programming!  In this class you will learn how to compete in programming contests such as ICPC,
Code Forces, and Hacker Rank.  *Is this class for you?  Read on to find out...*

*** What Are the Benefits of Competitive Programming?

Participating in coding contests has benefits!

  You will
  - build confidence in your coding skills,
  - increase your coding speed,
  - be ready to crush a coding interview,
  - and quite possibly make some friends!

*** But... I'm not very competitive, and besides, I'll never beat those top students!

That doesn't matter!  Whether you are just starting out or whether you are competing for a chance at the World Finals,
the only person you're really trying to beat is yourself.  The goal is to try hard, do a little bit better than last time,
or perhaps learn something that will help you next time.  You can do practice problems on your own, but there's nothing
like a contest to keep you honest.

*** Am I ready for this course?

The only prerequisite is that we assume you know how to program.  We don't even assume you're any good at it... this course
will help with that part.  But if you have programmed in Python, C, or C++ then you are ready for this course.

It does help if you've taken data structures and a theory course... but you can get started now and take those later as you
get stronger.

** Getting Started
:PROPERTIES:
:EXPORT_FILE_NAME: getting-started
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 2 :date 2022-08-22 :publishdate 2022-07-01
:END:

*** How Do I Get Started?

  - Join the CampusWire forum.  If you registered before class started, you should have gotten an invite.  If you registered late,
    or did not get the invite, you need to email the instructor.
  - It is recommended that you get these books:
    - [[https://cpbook.net][Competitive Programming 4]].  It is a two book set.
    - [[https://link.springer.com/book/10.1007/978-3-319-72547-5][Guide to Competitive Programming]].  As of this writing the PDF is free.
  - Register on [[https://codeforces.com][Code Forces]].  Your username *will be visible* to other students; you can create a "throwaway"
    account if you want just for this course.
    - Once you are registered, join [[https://codeforces.com/group/PHxDiFeaeq/contests][the class group]].  This is where your problems
      will be hosted.

*** How do I get good at this?

Practice.  A lot.  But do it efficiently...

  - Attend contests as much as you can.
    - [[https://codeforces.com][Code Forces]] has two hour long contests usually once or twice a week, for instance.
    - After the contest is over, read the commentary, both for the problems you solved, and the problems you attempted and could not solve.
    - Upsolve the ones you couldn't do.  (I don't know why they call it upsolving.)  This means that you go back to the computer, finish
      your solution, and submit it until you get it accepted.
  - Solve practice problems
    - This has a similar feel, but in this case it's okay get help.  If you are solving UVa problems you can use the UDebug and UHunt
      sites for extra hints / sample inputs.

** Syllabus
:PROPERTIES:
:EXPORT_FILE_NAME: syllabus
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 3 :date 2022-08-22 :publishdate 2022-07-01
:END:

This is where the syllabus will be.

* Lectures
:PROPERTIES:
:HUGO_SECTION: lectures
:EXPORT_HUGO_SECTION: lectures
:END:

** Course Introduction
:PROPERTIES:
:ID:       d6691455-f4dc-44ec-b6ae-2b169766e1af
:EXPORT_FILE_NAME: course-introduction
:END:

Welcome to Competitive Programming!  Today we will talk about the benefits of competitive programming, the course structure, and the tools we will
use in the course.

** IO
:PROPERTIES:
:EXPORT_FILE_NAME: io
:END:

The first thing your program needs to do is read in the test data and convert it to an internal structure.
There are several patterns that test cases follow, and you will need to handle each one a bit differently.
It all comes down to knowing how much data you are going to get.  There are three primary ways you find this out:

- An explicit count
- A special marker (like a terminating zero)
- Simply getting an end-of-file

We will also talk about formatting options.

We don't have a video for this lecture, but here are some slides with all the content.

- [[/slides/io-slides.pdf][IO Slides]]
